### ISSUE TITLE
手动扣了一些素材

### ISSUE THREAD

**Issue by Mateoust** [GardenHamster/GenshinPray#1]
1.不太知道需要的素材要求。所以我使用了512×1024并采取了相对居中的的方式用PS扣了几张。不知道行不行,图片放在了下方，素材来源是米游社的抽卡截图。本身就有点糊吧。所以效果可能不太好。没问题的话我就抽空看看那些缺的扣一下。
2.另外就是后续是否会有api文档吗？
3.是否有Docker之类的容器化的想法呢？

文件：[素材.zip](https://github.com/GardenHamster/GenshinPray/files/7063951/default.zip)
图片：
![狼的末路](https://user-images.githubusercontent.com/46558043/131067657-6049882f-0cc6-4cb1-a975-cf32738bad06.png)
![风鹰剑](https://user-images.githubusercontent.com/46558043/131067690-cf6d99a9-dc3d-49de-ba4e-4750d1f22fdd.png)
![松籁响起之时](https://user-images.githubusercontent.com/46558043/131067694-aeb631d4-f1d6-45d3-bdf0-a47753626acc.png)
![天空之翼](https://user-images.githubusercontent.com/46558043/131067697-2f2dc66a-77bc-41b9-9545-cd688088737f.png)

**Comment by Mateoust** [comment]
> 也可以，那就根据传入的参数决定返回url还是base64好了。图片开一个定时器隔天清理就好了。

可行，不过大佬有想法做授权码的获取通道吗？因为我看到有鉴权的机制。比如web的获取申请？还是提供api从qqbot那边申请？昨天用了下感觉还是不错的。非常感谢大佬的付出，期待更完善的版本~

**Comment by GardenHamster** [comment]
> > 也可以，那就根据传入的参数决定返回url还是base64好了。图片开一个定时器隔天清理就好了。
> 
> 可行，不过大佬有想法做授权码的获取通道吗？因为我看到有鉴权的机制。比如web的获取申请？还是提供api从qqbot那边申请？昨天用了下感觉还是不错的。非常感谢大佬的付出，期待更完善的版本~

emmmm，授权的话我本来是打算直接在数据表加授权码就算了的，一个授权码对应一个群。授权通道要做成什么样的你有什么想法吗

**Comment by Mateoust** [comment]
> emmmm，授权的话我本来是打算直接在数据表加授权码就算了的，一个授权码对应一个群。授权通道要做成什么样的你有什么想法吗

这个也可以吧。自己用在数据库里写这个问题不大。我的想法大概是做成web界面之类的如何？我看到有自定义卡池的更换。感觉可以使用web界面更换卡池配置。保底次数等配置？ 然后将授权码的获取这个也加入web的配置里面？这样可能会直观一些。但是也会增加代码量和复杂程度吧。不过我感觉始终还是你那个“直接在数据表加”比较好。人工审核这样也比较符合吧。想了下用qqbot申请。可能会出现各种问题。所以还是觉得弄个web的前端界面提交数据库 (类似于后台系统) 或者 直接改数据库的方法可能会好点。

**Comment by GardenHamster** [comment]
也行，先把主要功能做了，后面再用vue写一套前台好了

**Comment by Mateoust** [comment]
> 也行，先把主要功能做了，后面再用vue写一套前台好了

辛苦了，估计代码量不小，我不太了解.net。所以帮不上忙
