### ISSUE TITLE
神里绫人

### ISSUE THREAD

**Issue by MiniGrayGay** [GardenHamster/GenshinPray#11]
绫人的gacha图是不是左上角武器缺了点

[UI_Gacha_EquipIcon_Sword_Amenoma.zip](https://github.com/GardenHamster/GenshinPray/files/8378985/UI_Gacha_EquipIcon_Sword_Amenoma.zip)

**Comment by MiniGrayGay** [comment]
![UI_Gacha_AvatarIcon_Ayato](https://user-images.githubusercontent.com/64829926/160795612-f01a517d-1ce9-4b80-baab-f82163b3e42e.png)
![UI_Gacha_AvatarImg_Ayato](https://user-images.githubusercontent.com/64829926/160795630-2e02dfb4-7e1c-430d-8fc5-a4aa8fce5077.png)
![UI_Gacha_EquipIcon_Sword_Amenoma](https://user-images.githubusercontent.com/64829926/160795643-f2a2ce17-21a3-4c59-b0b9-6721da1cbb88.png)

**Comment by MiniGrayGay** [comment]
先润了

**Comment by GardenHamster** [comment]
![image](https://user-images.githubusercontent.com/89188316/160815748-02d3c21a-4cb2-4994-abc1-be50c133410f.png)凌人的gacha图顶部是透明的，缺了一点也正，我的目标只是做的比较像而已，没有想过要100%还原

**Comment by MiniGrayGay** [comment]
哈哈，确实（
