### ISSUE TITLE
导入数据库失败

### ISSUE THREAD

**Issue by MiniGrayGay** [GardenHamster/GenshinPray#12]
宝塔Linux环境，启动时会提示用户名和密码不能相同导入数据库失败，试了下，好像导入的时候需要root用户才能正确导入

**Comment by GardenHamster** [comment]
相关报错贴出来看下

**Comment by GardenHamster** [comment]
可能是权限问题吧，用root账号会出问题吗

**Comment by MiniGrayGay** [comment]
root账户不会出现问题，（但是试过，也不能数据库名字是root），用root创建完再切回普通用户，功能都正常用，数据库也能正常记录
