### ISSUE TITLE
全角色池与全武器池初始化时使用的getByGoodsType方法漏了GoodsID

### ISSUE THREAD

**Issue by Natsukage** [GardenHamster/GenshinPray#15]
如题，全角色池与武器池使用getByGoodsType方法从goods而不是从pond_goods检索数据，这个方法中在Select时漏掉了GoodsID信息，返回的YSGoodsItem中所有物品的GoodsID均为0
导致全角色池与全武器池出货后，AddMemberGoods时添加的记录中的GoodsID也为0而不是物品本身的ID。进而导致出货无法正常计入角色的已有库存和事后的角色祈愿记录查询。
fix：
```` SQL
sqlBuilder.Append(" select g.GoodsName,g.RareType,g.GoodsType,g.GoodsSubType,g.Id as GoodsId from goods g");
...
````

**Comment by GardenHamster** [comment]
啊，抱歉，没仔细做过测试，等下我改回来，感谢反馈
