### ISSUE TITLE
Base64时不保留文件

### ISSUE THREAD

**Issue by MiniGrayGay** [GardenHamster/GenshinPray#16]
rt，腾讯轻量姬子只有80G硬盘，出去杂七杂八的大概剩下30G可以用，塞到机器人之后，一晚上就把硬盘撑爆了，根本等不到凌晨4点删图片。能不能弄个参数输出只base64，本地不产生文件。

**Comment by GardenHamster** [comment]
修改了，在v0.6.1分支上。晚点我再打包发布出来

**Comment by MiniGrayGay** [comment]
嗯嗯
