### ISSUE TITLE
生成的图片颜色鬼畜

### ISSUE THREAD

**Issue by YidaozhanYa** [GardenHamster/GenshinPray#18]
![202204252143251870](https://user-images.githubusercontent.com/73830635/165101751-59f05ada-caea-49ca-9a26-1eef41774da1.jpg)
如图。生成的时候日志在不断重复这句话：libpng warning: iCCP: known incorrect sRGB profile

**Comment by YidaozhanYa** [comment]
使用 pngcrush 去除图片的色域信息后，libpng 不会报错，但生成的图片仍然鬼畜。
系统：Arch Linux
libpng 1.6.37    libjpeg 2.1.3

**Comment by GardenHamster** [comment]
建议还是用windows或者centos
