### ISSUE TITLE
单抽时，获得的武器名称文字显示不出来，乱码

### ISSUE THREAD

**Issue by xinxinyihao** [GardenHamster/GenshinPray#4]
单抽时，获得的武器名称文字显示不出来，显示框框。
linux环境
是我系统没有安装你用的字体的原因么？

**Comment by GardenHamster** [comment]
有截图吗,让我康康

**Comment by GardenHamster** [comment]
目前用的字体是微软雅黑

**Comment by xinxinyihao** [comment]
### 问题图片：
![202112200933533936](https://user-images.githubusercontent.com/41506567/146699696-aea7c81c-5d62-477a-be18-aaa1e3f37476.jpg)
### 字体图片：
![image](https://user-images.githubusercontent.com/41506567/146700073-cd1a1d07-966d-4d7f-b6ed-f56b33b369d0.png)
![image](https://user-images.githubusercontent.com/41506567/146700096-4f318f62-7da4-46dd-a44d-72950b75413e.png)
### 尝试解决：
就是这个样子，所有涉及到汉字的地方都会显示不出来，我的linux没有微软雅黑，然后我尝试从win系统里拿的的字体，安装了图片上面的那几个字体，没有解决。不知道是不是我安装的字体和你的不对版。
俺也不确定是不是字体的原因，如果是字体的，我想：
1、是不是可以在程序资源里面自带字体，然后代码指定字体，或者设置缺省字体，应该以后可以避免我这个问题（没用过.net，不清楚）
2、麻烦您提供一下您现在使用的字体，我再安装试试。
非常感谢

**Comment by xinxinyihao** [comment]
> 有截图吗,让我康康

发了截图了，在下面

**Comment by GardenHamster** [comment]
以后字体会再优化一下。我用这几个字体是可以的，你可以试试

**Comment by GardenHamster** [comment]
[msyh.zip](https://github.com/GardenHamster/GenshinPray/files/7743526/msyh.zip)
[msyhbd.zip](https://github.com/GardenHamster/GenshinPray/files/7743530/msyhbd.zip)
[msyhl.zip](https://github.com/GardenHamster/GenshinPray/files/7743531/msyhl.zip)
