### ISSUE TITLE
风鹰剑 512*1024

### ISSUE THREAD

**Issue by Natsukage** [GardenHamster/GenshinPray#7]
[风鹰剑.zip](https://github.com/GardenHamster/GenshinPray/files/7823764/default.zip)

其实原尺寸的导出图在内鬼网之类的地方都可以直接下到的
比如风鹰剑就在
https://genshin-impact.fandom.com/wiki/Aquila_Favonia
向下拖到Gallery处就是了
除了武器外，角色的2048*1024大图也都有。但是这个网站默认下的是webp格式，需要自己摸个脚本转png。

**Comment by Natsukage** [comment]
[webp2png.zip](https://github.com/GardenHamster/GenshinPray/files/7823854/webp2png.zip)
粗略能用的python转换，运行后直接将同目录下的webp转存为同名png文件。
或者用C#实现也可以，不过麻烦点…

**Comment by GardenHamster** [comment]
谢谢dalao，尺寸对上了，效果也可以

其实也不用特意转png，因为原本网站的素材就是png
https://static.wikia.nocookie.net/gensin-impact/images/8/88/Weapon_Aquila_Favonia_Wish.png/revision/latest/scale-to-width-down/512?cb=20210404075348

![image](https://user-images.githubusercontent.com/89188316/148481715-319d24e0-1383-4cb8-ab69-9ac8369dd0ac.png)![image](https://user-images.githubusercontent.com/89188316/148481715-319d24e0-1383-4cb8-ab69-9ac8369dd0ac.png)![image](https://user-images.githubusercontent.com/89188316/148481715-319d24e0-1383-4cb8-ab69-9ac8369dd0ac.png)

**Comment by Natsukage** [comment]
啊，看了一眼还真是。。
我直接从网页拖拽到桌面了它自动保存为了webp，我就没细想。刚看了下右键保存就可以直接存png了，丢人了。

以及有2个小bug昨晚我提了个pr，你看下吧233

**Comment by GardenHamster** [comment]
好的，有空我看看
![](https://user-images.githubusercontent.com/89188316/148481715-319d24e0-1383-4cb8-ab69-9ac8369dd0ac.png)
