### ISSUE TITLE
这个抽卡返回的star5Cost是什么意思？

### ISSUE THREAD

**Issue by xinxinyihao** [GardenHamster/GenshinPray#8]
![image](https://user-images.githubusercontent.com/41506567/151495876-00844e72-b41e-4489-be0d-9d11630c7368.png)

这个抽卡返回的star5Cost是什么意思？是一次保底中，抽到五星用了多少抽的意思么？

**Comment by GardenHamster** [comment]
是的

**Comment by xinxinyihao** [comment]
> 是的

老师你好，问几个问题：
1、上面这个截图是武器池子抽卡的数据，武器池为啥会存在第90次出金的情况，武器池子不是80就保底了么。

2、这个star5Cost是武器，角色、常驻三个池子都通用这一个变量么，我好像没在数据库看到这个段，这个是每次抽卡直接计算的么，三个池子可以保持独立的cost么，会不会是因为这个导致武器池90出金的？

3、就是概率不知道是怎么算的，我抽了快3000多次角色池子，绝大多数都是第90次出金，只有一两次不是的，这不太正常啊。

**Comment by GardenHamster** [comment]
单抽出五星的概率会大概在第70抽以后慢慢提高，这个目前并没有模拟

**Comment by GardenHamster** [comment]
武器祈愿返回的star5Cost会比实际的结果会多处10，这个晚点会改过来
